version: '3.8'

services:
  personal-site:
    image: ghcr.io/runonyourown/personal-site:latest
    container_name: personal-site
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - proxy
    environment:
      - NODE_ENV=${NODE_ENV}
      - SITE_URL=${SITE_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}

networks:
  proxy:
    external: true
